// frontend-pwa/react/src/pages/AdminApproval/index.js
import {useState, useRef, useEffect} from 'react'
import styles from './styles.module.css'
import approve from '../../assets/gifs/approve.gif'
import Loading from '../../components/Loading'
import Back from '../../components/Back'
import { useParams, useHistory } from 'react-router-dom'
import { Form } from '@unform/web'
import Input from '../../components/Form/Input'
import PromotionService from '../../services/PromotionService'
import Notification, { showToast } from '../../components/Notification'
import {Animated} from "react-animated-css";

import * as Yup from 'yup'
import Swal from 'sweetalert2'
import withReactContent from 'sweetalert2-react-content'

const AdminApproval = () => {
  const params = useParams();
  const formRef = useRef(null)
  const history = useHistory()
  const [loading, setLoading] = useState(false)
  const [promotion, setPromotion] = useState("")
  const [useToast, setToast] = useState(false);
  const MySwal = withReactContent(Swal)

  let loadingStyle = {
    background: 'none'
  }
  console.log(params.id)

  useEffect(() => {
    setLoading(true)
    PromotionService.getPromotionById(params.id).then((response) => {
      if(response.status === 200){
        setPromotion(response.data)
        setLoading(false)
      }
    })
  }, [params.id])

  async function handleSubmit(data){
    try {
      const schema = Yup.object().shape({
        soldBy: Yup.string().required('O local da venda é obrigatório').min(2, 'No mínimo 2 caracteres').max(20, 'No máximo 20 caracteres'),
        photo: Yup.string().required('A url da foto é obrigatória').min(5, 'No mínimo 5 caracteres'),
      }) 
      
       await schema.validate(data, {
        abortEarly: false
      })

      console.log(data)
      setLoading(true)
      PromotionService.putPromotion(params.id, data).then((response) => {
        if(response.status === 200){
          setLoading(false)
          MySwal.fire({
            icon: 'success',
            title: `Aprovada!`,
            text: `Obaa a promoção foi aprovada com sucesso e já encontra-se no feed :D`,
            showConfirmButton: false,
            timer: 4000,
            timerProgressBar: true
          }).then(()=>{
            history.push("/admin")
          })
        }
      }, () => {
        MySwal.fire({
          icon: 'error',
          title: 'Ocorreu um erro',
          text: 'Tente novamente mais tarde',
          showConfirmButton: false,
          timer: 4000,
          timerProgressBar: true
        }).then(()=>{
          history.push("/admin")
        })
      })

    } catch (err) {
      setToast(true)
      showToast({ type: "warning", message: "Ocorreu um erro no cadastro, por favor verifique os dados do formulário" });
      if (err instanceof Yup.ValidationError){
        const errorMessages = {}
        err.inner.forEach(error => {
          errorMessages[error.path] = error.message
        })
        formRef.current.setErrors(errorMessages)
      }
    }
  }

  function dontApprove(){
    MySwal.fire({
      title: 'Tem Certeza?',
      text: "Após reprovada, a promoção não estará mais disponivel!",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#42B983',
      cancelButtonColor: '#C6EAD9',
      confirmButtonText: 'Tenho certeza',
      cancelButtonText: "Cancelar"
    }).then((result)=>{
      if(result.isConfirmed){
        PromotionService.deletePromotion(params.id).then((response) => {
          if(response.status === 200){
            MySwal.fire({
              icon: 'success',
              title: 'Não Aprovada',
              text: 'A promoção foi reprovada com sucesso!',
              showConfirmButton: false,
              timer: 4000,
              timerProgressBar: true
            }).then(()=>{
              history.push("/admin")
            })
          }
        }, () => {
          MySwal.fire({
            icon: 'error',
            title: 'Ocorreu um erro',
            text: 'Tente novamente mais tarde',
            showConfirmButton: false,
            timer: 4000,
            timerProgressBar: true
          })
        })
      }
    })
  }

  return (
    <Animated animationIn="fadeIn" animationOut="fadeOut" isVisible={true}>
    <section className={"page"} >
      <Back/>
        <div className={"intro"}>
          <img src={approve} alt="promotion-approve" />
      </div>
      {loading ? <div className={"myDiv"} style={loadingStyle} >
        <Loading/>
      </div> : <div className={"myDiv"}>
          <h1>Sala de Aprovação</h1>
          <Form ref={formRef} onSubmit={handleSubmit} className={"myForm"}>
            <label htmlFor="name">Nome</label>
            <input value={promotion.name} name="name" disabled type="text"/>
            <label htmlFor="description">Descrição</label>
            <textarea value={promotion.description} disabled type="text" cols="30" rows="10"></textarea>
            <label htmlFor="price">Preço</label>
            <input value={promotion.price} type="number" disabled/>
            <label htmlFor="link">Link</label>
            <input value={promotion.urlLink} type="text" disabled />
            <label htmlFor="cupom">Cupom</label>
            <input value={promotion.voucher !== "" ? promotion.voucher : "Sem cupom"} type="text" disabled />
            <Input label="Vendido por" type="text" name="soldBy" placeholder="Exemplo: Magalu"/>
            <Input label="Foto do Item" type="text" name="photo" placeholder="Copie o link da imagem e cole aqui"/>
            <div className={styles.myButtons}>
              <button className={"btn"} type="submit">Aprovar</button>
              <button onClick={dontApprove} className={"btn"}>Não Aprovar</button>
            </div>
          </Form>
      </div>} 
      {useToast ? <Notification/> : null}
</section>
</Animated>
  )
}

export default AdminApproval

// frontend-pwa/angular/src/app/pages/admin-approval/admin-approval.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { PromotionService } from 'src/app/services/promotion.service';
import { Promotion } from 'src/app/models/Promotion';
import Swal from 'sweetalert2'



@Component({
  selector: 'app-admin-approval',
  templateUrl: './admin-approval.component.html',
  styleUrls: ['./admin-approval.component.css']
})
export class AdminApprovalComponent implements OnInit {

  public promotionID: number;
  public promotion: Promotion; 
  public approvalPromotionForm: FormGroup;
  public loading: boolean;
  public approveRoom: boolean;


  constructor(private ativatedRoute: ActivatedRoute, private promotionService: PromotionService, private router: Router) {
  
    this.ativatedRoute.params.subscribe((params) => {
      this.promotionID = params['id'];
    })
    this.approvalPromotionForm = new FormGroup({
      soldBy: new FormControl('', [Validators.required, Validators.minLength(2), Validators.maxLength(20)]),
      photo: new FormControl('', [Validators.required, Validators.minLength(7)])
    });
   }

  ngOnInit(): void {
    this.loading = true;
    this.approveRoom = false;
    this.promotionService.getPromotionById(this.promotionID).subscribe((data) => {
      this.promotion = data;
      this.loading = false;
      this.approveRoom = true;
    })
   
  }

  noApprove(){
    Swal.fire({
      title: 'Tem Certeza?',
      text: "Após reprovada, a promoção não estará mais disponivel!",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#ED7272',
      cancelButtonColor: '#ED9292',
      confirmButtonText: 'Tenho certeza',
      cancelButtonText: "Cancelar"
    }).then((result) => {
      if (result.isConfirmed) {
        this.promotionService.deletePromotion(this.promotionID).subscribe((response) => {
          if(response){
            Swal.fire({
              icon: 'success',
              title: 'Não Aprovada',
              text: 'A promoção foi reprovada com sucesso!',
              showConfirmButton: false,
              timer: 4000,
              timerProgressBar: true
            }).then(() => {
              this.router.navigate(['/admin'])
            })
          }
        }, (err) => {
            Swal.fire({
              icon: 'error',
              title: 'Ocorreu um erro',
              text: 'Tente novamente mais tarde',
              showConfirmButton: false,
              timer: 4000,
              timerProgressBar: true
            })
        })
      }
    })
  }

  onSubmit(){
    const promotion = new Promotion();
    promotion.soldBy = this.approvalPromotionForm.get('soldBy').value;
    promotion.photo = this.approvalPromotionForm.get('photo').value;
    this.loading = true;
    this.approveRoom = false;
    this.promotionService.putPromotion(this.promotionID, promotion).subscribe((response)=>{
      if(response !== null){
        this.loading = false;
        Swal.fire({
          icon: 'success',
          title: `Aprovada!`,
          text: `Obaa a promoção foi aprovada com sucesso e já encontra-se no feed :D`,
          showConfirmButton: false,
          timer: 4000,
          timerProgressBar: true
        }).then(() => {
          this.approveRoom = true;
          this.router.navigate(['/admin'])})
      }
    }, (err) => {
      this.loading = false;
      Swal.fire({
        icon: 'error',
        title: 'Ocorreu um erro',
        text: 'Tente novamente mais tarde',
        showConfirmButton: false,
        timer: 4000,
        timerProgressBar: true
      }).then(() => {
        this.approveRoom = true;
        this.router.navigate(['/admin'])})
    })
  }

  isFormFieldInvalid(field: string) {
    const ctrl = this.approvalPromotionForm.get(field);
    return ctrl?.dirty && ctrl?.touched && ctrl?.dirty ;
  }

  hasError(field: string, error: string) {
    const ctrl = this.approvalPromotionForm.get(field);
    return ctrl?.dirty && ctrl?.hasError(error);
  }

}

<section class="approval-page animate__animated animate__fadeIn" >
  <div class="approveRoom" *ngIf="promotion && approveRoom">
    <back></back>
    <div class="intro">
      <img src="../../../assets/gifs/approve.gif" alt="promotion-approve" />
    </div>
    <div class="my-div" *ngIf="approveRoom">
      <h1>Sala de Aprovação</h1>
      <form [formGroup]="approvalPromotionForm" (submit)="onSubmit()" novalidate class="my-form">
        <label for="name">Nome</label>
        <input type="text" disabled value="{{promotion.name}}">
        <label for="password">Descrição</label>
        <textarea type="text" disabled value="{{promotion.description ? promotion.description : 'Sem descrição'}}" cols="30" rows="10"></textarea>
        <label for="price">Preço</label>
        <input type="number" disabled value="{{promotion.price}}">
        <label for="link">Link</label>
        <input type="text" disabled value="{{promotion.urlLink}}">
        <label for="cupom">Cupom</label>
        <input type="text" disabled value="{{promotion.voucher ? promotion.voucher : 'Sem cupom'}}">
        <label for="soldBy">Vendido por</label>
        <input type="text" formControlName="soldBy" [class.is-invalid]="isFormFieldInvalid('soldBy')" placeholder="Exemplo: Magalu">
        <div class="messages">
          <small class="text-danger" *ngIf="hasError('soldBy', 'required')">*Campo obrigatório</small>
          <small class="text-danger" *ngIf="hasError('soldBy', 'minlength')">*Tamanho mínimo de 2 caracteres</small>
          <small class="text-danger" *ngIf="hasError('soldBy', 'maxlength')">*Tamanho máximo de 20 caracteres</small>
        </div>
        <label for="photo">Foto do Item</label>
        <input type="text" formControlName="photo" [class.is-invalid]="isFormFieldInvalid('photo')" placeholder="Copie o link da imagem e cole aqui">
        <div class="messages">
          <small class="text-danger" *ngIf="hasError('photo', 'required')">*Campo obrigatório</small>
          <small class="text-danger" *ngIf="hasError('photo', 'minlength')">*Tamanho mínimo de 7 caracteres</small>
        </div>
        <div class="my-buttons">
          <button class="btn" type="submit" [disabled]="!approvalPromotionForm.valid">Aprovar</button>
        </div>
      </form>
      <button class="btn" (click)="noApprove()">Não Aprovar</button>
    </div>
  </div>
  <div [ngStyle]="{'background' : loading ? 'none' : '#ED9292'}" class="my-loading" *ngIf="loading">
    <loading></loading>
  </div>
</section>
