// frontend-pwa/react/src/pages/AdminApproval/index.js
import {useState, useRef, useEffect} from 'react'
import styles from './styles.module.css'
import approve from '../../assets/gifs/approve.gif'
import Loading from '../../components/Loading'
import Back from '../../components/Back'
import { useParams, useHistory } from 'react-router-dom'
import { Form } from '@unform/web'
import Input from '../../components/Form/Input'
import PromotionService from '../../services/PromotionService'
import Notification, { showToast } from '../../components/Notification'
import {Animated} from "react-animated-css";

import * as Yup from 'yup'
import Swal from 'sweetalert2'
import withReactContent from 'sweetalert2-react-content'

const AdminApproval = () => {
  const params = useParams();
  const formRef = useRef(null)
  const history = useHistory()
  const [loading, setLoading] = useState(false)
  const [promotion, setPromotion] = useState("")
  const [useToast, setToast] = useState(false);
  const MySwal = withReactContent(Swal)

  let loadingStyle = {
    background: 'none'
  }
  console.log(params.id)

  useEffect(() => {
    setLoading(true)
    PromotionService.getPromotionById(params.id).then((response) => {
      if(response.status === 200){
        setPromotion(response.data)
        setLoading(false)
      }
    })
  }, [params.id])

  async function handleSubmit(data){
    try {
      const schema = Yup.object().shape({
        soldBy: Yup.string().required('O local da venda é obrigatório').min(2, 'No mínimo 2 caracteres').max(20, 'No máximo 20 caracteres'),
        photo: Yup.string().required('A url da foto é obrigatória').min(5, 'No mínimo 5 caracteres'),
      }) 
      
       await schema.validate(data, {
        abortEarly: false
      })

      console.log(data)
      setLoading(true)
      PromotionService.putPromotion(params.id, data).then((response) => {
        if(response.status === 200){
          setLoading(false)
          MySwal.fire({
            icon: 'success',
            title: `Aprovada!`,
            text: `Obaa a promoção foi aprovada com sucesso e já encontra-se no feed :D`,
            showConfirmButton: false,
            timer: 4000,
            timerProgressBar: true
          }).then(()=>{
            history.push("/admin")
          })
        }
      }, () => {
        MySwal.fire({
          icon: 'error',
          title: 'Ocorreu um erro',
          text: 'Tente novamente mais tarde',
          showConfirmButton: false,
          timer: 4000,
          timerProgressBar: true
        }).then(()=>{
          history.push("/admin")
        })
      })

    } catch (err) {
      setToast(true)
      showToast({ type: "warning", message: "Ocorreu um erro no cadastro, por favor verifique os dados do formulário" });
      if (err instanceof Yup.ValidationError){
        const errorMessages = {}
        err.inner.forEach(error => {
          errorMessages[error.path] = error.message
        })
        formRef.current.setErrors(errorMessages)
      }
    }
  }

  function dontApprove(){
    MySwal.fire({
      title: 'Tem Certeza?',
      text: "Após reprovada, a promoção não estará mais disponivel!",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#42B983',
      cancelButtonColor: '#C6EAD9',
      confirmButtonText: 'Tenho certeza',
      cancelButtonText: "Cancelar"
    }).then((result)=>{
      if(result.isConfirmed){
        PromotionService.deletePromotion(params.id).then((response) => {
          if(response.status === 200){
            MySwal.fire({
              icon: 'success',
              title: 'Não Aprovada',
              text: 'A promoção foi reprovada com sucesso!',
              showConfirmButton: false,
              timer: 4000,
              timerProgressBar: true
            }).then(()=>{
              history.push("/admin")
            })
          }
        }, () => {
          MySwal.fire({
            icon: 'error',
            title: 'Ocorreu um erro',
            text: 'Tente novamente mais tarde',
            showConfirmButton: false,
            timer: 4000,
            timerProgressBar: true
          })
        })
      }
    })
  }

  return (
    <Animated animationIn="fadeIn" animationOut="fadeOut" isVisible={true}>
    <section className={"page"} >
      <Back/>
        <div className={"intro"}>
          <img src={approve} alt="promotion-approve" />
      </div>
      {loading ? <div className={"myDiv"} style={loadingStyle} >
        <Loading/>
      </div> : <div className={"myDiv"}>
          <h1>Sala de Aprovação</h1>
          <Form ref={formRef} onSubmit={handleSubmit} className={"myForm"}>
            <label htmlFor="name">Nome</label>
            <input value={promotion.name} name="name" disabled type="text"/>
            <label htmlFor="description">Descrição</label>
            <textarea value={promotion.description} disabled type="text" cols="30" rows="10"></textarea>
            <label htmlFor="price">Preço</label>
            <input value={promotion.price} type="number" disabled/>
            <label htmlFor="link">Link</label>
            <input value={promotion.urlLink} type="text" disabled />
            <label htmlFor="cupom">Cupom</label>
            <input value={promotion.voucher !== "" ? promotion.voucher : "Sem cupom"} type="text" disabled />
            <Input label="Vendido por" type="text" name="soldBy" placeholder="Exemplo: Magalu"/>
            <Input label="Foto do Item" type="text" name="photo" placeholder="Copie o link da imagem e cole aqui"/>
            <div className={styles.myButtons}>
              <button className={"btn"} type="submit">Aprovar</button>
              <button onClick={dontApprove} className={"btn"}>Não Aprovar</button>
            </div>
          </Form>
      </div>} 
      {useToast ? <Notification/> : null}
</section>
</Animated>
  )
}

export default AdminApproval

// frontend-pwa/vue/src/views/AdminApproval.vue
<template>
  <section class="approval-page">
    <Back class="back-btn"/>
  <div class="approveRoom">
    <div class="intro">
      <img src="../assets/gifs/approve.gif" alt="promotion-approve" />
    </div>
    <div class="my-div" v-if="approveRoom">
      <h1>Sala de Aprovação</h1>
      <form class="my-form" @submit.prevent="approve">
        <label for="name">Nome</label>
        <input type="text" name="nome" id="name" disabled v-model="promotion.name">
        <label for="description">Descrição</label>
        <textarea type="text" name="descrição" id="description" disabled  cols="30" rows="10" v-model="promotion.description"></textarea>
        <label for="price">Preço</label>
        <input type="number" name="preço" id="price" v-model="promotion.price" disabled>
        <label for="urlLink">Link</label>
        <input type="text" name="link" id="urlLink" disabled   v-model="promotion.urlLink" >
        <label for="voucher">Cupom</label>
        <input type="text" name="cupom" id="voucher" v-model="promotion.voucher" disabled >
        <label for="soldBy">Vendido por</label>
        <input type="text" id="soldBy" name="vendido" v-model="promotion.soldBy" placeholder="Exemplo: Magalu" v-validate="'required|min:2|max:20'">
        <span>{{errors.first('vendido')}}</span>
        <label for="urlPhoto">Foto do Item</label>
        <input type="text" id="urlPhoto" name="foto" v-model="promotion.urlPhoto" placeholder="Copie o link da imagem e cole aqui" v-validate="'required|min:5'">
        <span>{{errors.first('foto')}}</span>
        <div class="my-buttons">
          <button class="btn" :disabled="errors.any()" type="submit">Aprovar</button>
        </div>
      </form>
      <button @click="dontApprove" class="btn">Não Aprovar</button>
    </div>
     <div class="my-div" v-if="loading">
      <loading></loading>
    </div>
  </div>
  </section>
</template>

<script>
import Back from '@/components/Back.vue'
import Loading from "@/components/Loading.vue"
import PromotionService from '../services/PromotionService'
export default {
  name: 'AdminApproval',
  components: {
    Back,
    'loading': Loading
  },
  data(){
    return{
      approveRoom: true,
      loading: false,
      promotion:{
        name: "",
        description: "",
        price: "",
        urlLink: "",
        voucher: "",
        soldBy: "",
        urlPhoto: ""
      }
    }
  },
  created(){
    this.loading = true
    this.approveRoom = false
    PromotionService.getPromotionById(this.$route.params.id).then((response) => {
      this.loading = false;
      this.approveRoom = true
      if(response.status === 200){
        this.promotion.name = response.data.name
        this.promotion.description = response.data.description ? response.data.description : 'Sem descrição'
        this.promotion.price = response.data.price
        this.promotion.urlLink = response.data.urlLink
        this.promotion.voucher = response.data.voucher ? response.data.voucher : 'Sem cupom'
      }
    })
  },
  methods: {
    approve(){
      this.$validator.validateAll().then(isValid =>{
         if (!isValid) {
          this.$toastr('warning', {msg: 'Ocorreu um erro na aprovação, por favor verifique os dados do formulário', title: 'Formulário incompleto', timeout: 5000,})
        }else{
          const restPromotion = {
            soldBy: this.promotion.soldBy,
            photo: this.promotion.urlPhoto
          }
          PromotionService.putPromotion(this.$route.params.id, restPromotion).then((response) => {
            if(response.status === 200){
              this.loading = false;
              this.$swal({
              icon: 'success',
              title: `Aprovada!`,
              text: `Obaa a promoção foi aprovada com sucesso e já encontra-se no feed :D`,
              showConfirmButton: false,
              timer: 4000,
              timerProgressBar: true
            }).then(()=>{
              this.approveRoom = true;
              this.$router.push('/admin')
            })
            }
          }, () => {
            this.loading = false;
            this.$swal({
              icon: 'error',
              title: 'Ocorreu um erro',
              text: 'Tente novamente mais tarde',
              showConfirmButton: false,
              timer: 4000,
              timerProgressBar: true
            }).then(()=>{
              this.approveRoom = true;
              this.$router.push('/admin')
            })
          })
        }
      })
    },
    dontApprove(){
      this.$swal({
          title: 'Tem Certeza?',
          text: "Após reprovada, a promoção não estará mais disponivel!",
          icon: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#42B983',
          cancelButtonColor: '#C6EAD9',
          confirmButtonText: 'Tenho certeza',
          cancelButtonText: "Cancelar"
        }).then((result) => {
          if (result.isConfirmed){
            PromotionService.deletePromotion(this.$route.params.id).then((response) => {
              if(response.status == 200){
                this.$swal({
              icon: 'success',
              title: 'Não Aprovada',
              text: 'A promoção foi reprovada com sucesso!',
              showConfirmButton: false,
              timer: 4000,
              timerProgressBar: true
              }).then(()=>{
                this.$router.push('/admin')
              })
              }
            }, () =>{
              this.$swal({
              icon: 'error',
              title: 'Ocorreu um erro',
              text: 'Tente novamente mais tarde',
              showConfirmButton: false,
              timer: 4000,
              timerProgressBar: true
            })
            })
          }
        })
    }
  }

}
</script>

<style scoped>

.approval-page {
  display: flex;
  width: 100%;
  height: calc(100vh - 8rem);
  user-select: none;
}

.intro {
  width: 50%;
  display: flex;
  justify-content: center;
  align-items: center;
}

.my-div{
  width: 50%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: min-content;
 
}

h1{
  text-align: center;
  font-size: 2rem;
  color: #42B983;
  margin-top: 1rem;
}

.text-danger{
  font-size: 12px;
  color: red;
}

.my-form{
  display: flex;
  flex-direction: column;
  width: 50%;
}

.approveRoom{
  display: flex;
  width: 100%;
}

.btn{
  max-width: 300px;
  margin: 0 auto;
  margin-left: auto;
  margin-right: auto;
  width: 100%;
}

span{
  display: block;
  text-align: center;
}

input{
  margin-bottom: 1rem;
}

input:disabled:hover{
  transform: scale(1);
  cursor: not-allowed;
  user-select: none;
  border-color: gray;
}

textarea{
  margin-bottom: 1rem;
}

textarea:disabled:hover{
  transform: scale(1);
  cursor: not-allowed;
  border-color: gray;
}

button{
  margin-bottom: 1rem !important;
}

h1{
  padding: 5px;
}

.my-loading{
  margin: 0 auto;
}

@media screen and (max-width: 700px){
  .approval-page{
    width: 100%;
    flex-direction: column;
  }
  .approveRoom{
    display: block;
  }

  .intro{
    width: 100%;
  }

  .my-div{
    width: 100%;
    height: auto;
    color: #42B983;
    background: #C6EAD9;
  }

  .my-form{
    width: 80%;
  }

  img {
    width: 100%;
    max-width: 500px;
  }
}

</style>
