// frontend-pwa/react/src/components/Header/index.js
import {useContext} from 'react'
import styles from './styles.module.css'
import logo from '../../assets/logo.svg'
import {ReactComponent as AddPromotion} from '../../assets/icons/add.svg'
import {ReactComponent as Check} from '../../assets/icons/check.svg'
import {ReactComponent as Home} from '../../assets/icons/home.svg'
import {ReactComponent as Logout} from '../../assets/icons/logout.svg'
import {useHistory} from "react-router-dom";
import { GlobalContext } from '../../hooks/GlobalContext'
import AuthService from '../../services/AuthService'

const Header = () => {
  const context = useContext(GlobalContext)
  const history = useHistory();
  const {authorized,setAuthorized,admin,setAdmin} = context;

  function logOut(){
    AuthService.logout()
    setAuthorized(false)
    setAdmin(false)
    history.push('/')
  }
  function addPromotion(){
    history.push('/share-promotion')
    
  }
  function home(){
    history.push('/')
  }
  function goToAdmin(){
    history.push('/admin')
  }
  function login(){
    history.push('/login')
 
  }

  return (
    <header className={styles.myHeader}>
      <div>
        <img onClick={home} className={styles.myLogo} src={logo} alt="promotion-logo" />
      </div>
      {authorized && !admin && <div className={styles.buttons}>
        <button onClick={home} id="span-btn" className={"mobile"}><Home/></button>
        <button onClick={addPromotion} id="span-btn" className={"mobile"}><AddPromotion/></button>
        <button onClick={logOut} id="span-btn" className={"mobile"}><Logout/></button>
      </div>}
      {authorized && admin && <div className={styles.buttons}>
      <button onClick={home} id="span-btn" className={"mobile"}><Home/></button>
      <button onClick={goToAdmin} id="span-btn" className={"mobile"}><Check/></button>
      <button onClick={logOut} id="span-btn" className={"mobile"}><Logout/></button>
      </div>}
      {!authorized && !admin && <div>
        <button onClick={login} className={"btn"}>Login</button>
      </div>}
    </header>
  )
}

export default Header

// frontend-pwa/angular/src/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from 'src/app/services/auth.service';
import {EmitterService} from '../../services/emitter.service'

@Component({
  selector: 'my-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {

  public logged: boolean;
  public admin: boolean;

  constructor(private route: Router, private authService: AuthService, private emitter: EmitterService) { 
    this.logged = false;
    this.admin = false;
    if( this.authService.getRole() === 'ADMIN' && this.authService.getToken()){
      this.logged = true;
      this.admin = true;
    }

    if(this.authService.getRole() === 'CLIENT' && this.authService.getToken()){
      this.logged = true;
      this.admin = false;
    }
  }

  ngOnInit(): void {
    this.emitter.getValues().subscribe((data) => data.forEach(element => {
      this.logged = element.logged;
      this.admin = element.admin;
    }));
     
  }

  approvePromotion(){
    this.route.navigate(['/admin'])
  }

  addPromotion(){
    this.route.navigate(['/share'])
  }

  logOut(){
    this.logged = false;
    this.authService.logout();
    this.route.navigate(['/home'])
  }

  goToLogin(){
    this.route.navigate(['/login'])

  }

  goToHome(){
    this.route.navigate(['/home'])
  }

}

<header class="myHeader">
  <div>
    <img class="myLogo" src="../../../assets/logo.svg" alt="promotion-logo">
  </div>
  <div class="buttons" *ngIf="logged && admin">
    <button id="span-btn" (click)="goToHome()" class=" mobile"><span class="material-icons-outlined">
      cottage
      </span></button>
    <button id="span-btn" (click)="approvePromotion()" class=" mobile"><span class="material-icons-outlined">
      task_alt
      </span></button>
    <button (click)="logOut()" class=" mobile"><span class="material-icons-outlined">
      logout
      </span></button>
  </div>
  <div class="buttons" *ngIf="logged && !admin">
    <button id="span-btn" (click)="goToHome()" class=" mobile"><span class="material-icons-outlined">
      cottage
      </span></button>
    <button id="span-btn" (click)="addPromotion()" class=" mobile"><span class="material-icons-outlined">
      add
      </span></button>
    <button (click)="logOut()" class=" mobile"><span class="material-icons-outlined">
      logout
      </span></button>
  </div>
  <div *ngIf="!logged && !admin">
    <button (click)="goToLogin()" class="btn">Login</button>
  </div>
</header>
