// frontend-pwa/angular/src/app/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Promotion } from 'src/app/models/Promotion';
import { PromotionService } from 'src/app/services/promotion.service';
import { EmitterService } from 'src/app/services/emitter.service';


@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  public promotions: Array<Promotion> = [];
  public loading: boolean;

  constructor(private router: Router, private promotionService: PromotionService, private emitter: EmitterService) {
    this.loading = false;
   }

  ngOnInit(): void {
    this.loading = true;
    this.promotionService.getActivesPromotions().subscribe((response) =>{
      this.loading = false;
      response.forEach((data) => {
        this.promotions.push(data);
      })
    })
    
  }

  redirectTo(promotion) {
    this.router.navigate(['/promotion', promotion.id]);
  }

  goToWebSite(urlLink){
    return window.open(urlLink, '_blank') 
  }

  likePromotion(e, i){
    this.promotionService.like(e.id).subscribe((res) => {
      this.promotions[i] = res;
    })
  }

}

<section class="home animate__animated animate__fadeIn">
    <div class="list" *ngIf="promotions?.length > 0">
      <div class="my-promotion" *ngFor="let promotion of promotions; let i = index">
        <div class="card-info">
            <like [likes]="promotion.numberLikes" class="like" [promotionID]="promotion.id" (update)="likePromotion($event, i)"></like>
        <div (click)="redirectTo(promotion)" class="my-img">
            <img [src]=promotion.photo alt="card-img">
        </div>
        <div class="my-price">
            <p>{{promotion.price | currency:'BRL':true}}</p>
        </div>
          <div class="my-info">
                <h3 (click)="redirectTo(promotion)">{{promotion.name}}</h3>
                <div class="my-local">
                    <p>Vendido por {{promotion.soldBy}}</p>
                    <button (click)=goToWebSite(promotion.urlLink) class="my-link">Link</button>
                </div>
          </div>
        </div>
        <div class="dock">
            <div class="person">
                <ngx-avatar bgColor="#F4E6E6" fgColor="#ED9292" class="my-avatar"[name]="promotion.user.firstName" size="32"> </ngx-avatar>
                <div class="data">
                    <p>Postado por {{promotion.user.firstName}}</p>
                    <p>{{promotion.date | dateAgo}}</p>
                </div>
            </div>
          </div>
      </div>
    </div>
    <div class="list" *ngIf="promotions?.length  === 0 && !loading">
        <div class="noPromotion">
            <h1>Sem Promoções publicadas :(</h1>
        </div>
      </div>
    <div class="list" *ngIf="loading">
        <loading></loading>
    </div>
  </section>

// frontend-pwa/react/src/pages/Home/index.js
import {useState, useEffect} from 'react'
import './home.css'
import Avatar from 'react-avatar';
import { useHistory } from 'react-router-dom'
import PromotionService from '../../services/PromotionService';
import Loading from '../../components/Loading';
import toCurrency from '../../filters/toCurrency'
import dateAgo from '../../filters/dateAgo'
import Like from '../../components/Like';
import {Animated} from "react-animated-css";

const Home = () => {

  const history = useHistory()
  const [loading, setLoading] = useState(false)
  const [noPromotions, setNoPromotions] = useState(false)
  const [promotions, setPromotions] = useState([])

  useEffect(() => {
    setLoading(true)
    PromotionService.getActivesPromotions().then((response) => {
      if(response.status === 200){
        setLoading(false)
        if(response.data.length === 0){
          setNoPromotions(true)
        }
        response.data.forEach((data)=>{
          setPromotions(promotions => promotions.concat(data));
        })
      }
    })
  }
  , [])

  function goToWebSite(urlLink){
    return window.open(urlLink, '_blank') 
  }

  function goToPromotion(id){
    history.push(`/promotion/${id}`)
  }


  return (
    <Animated animationIn="fadeIn" animationOut="fadeOut" isVisible={true}>
        <section className="home">
      {loading ? <div className="list">
        <Loading/>
    </div> : <div className="list">
    {promotions.map((promotion,index) => (
      <div key={index} className="myPromotion">
      <div onClick={() => goToPromotion(promotion.id)} className="cardInfo">
        <div className='like'>
          <Like likes={promotion.numberLikes}></Like>
        </div>
        <div className="myInfo">
              <h3 onClick={() => goToPromotion(promotion.id)}> {promotion.name}</h3>
              <div className="myLocal">
                  <p>Vendido por {promotion.soldBy}</p>
                  <button onClick={() => {goToWebSite(promotion.urlLink)}} className="myLink">Link</button>
              </div>
        </div>
      <div className="promotionImg">
          <img src={promotion.photo} alt="card-img"/>
      </div>
      <div className="myPrice">
          <p>{toCurrency(promotion.price)}</p>
      </div>
        
      </div>
      <div className="dock">
          <div className="person">
            <Avatar color="#beebf7" name={promotion.user.firstName} size="35" round={true} />
              <div className="data">
                <p>Enviado por {promotion.user.firstName}</p>
                <p>{dateAgo(promotion.date)}</p>
              </div>
          </div>
        </div>
    </div>
    ))}
    </div>}

    {noPromotions && !loading ? <div className="list">
    <div className="noPromotion">
      <h1>Sem Promoções publicadas :(</h1>
    </div>
  </div> : null }
    
  </section>
    </Animated>

  )
}
export default Home
