// frontend-pwa/angular/src/app/components/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import {EmitterService} from '../../services/emitter.service'
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { UserService } from 'src/app/services/user.service';
import { User } from 'src/app/models/User';
import { AuthService } from 'src/app/services/auth.service'
import { Router } from '@angular/router';
import Swal from 'sweetalert2'


@Component({
  selector: 'register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {

  public open:boolean;
  public loading: boolean;
  public registerForm: FormGroup;

  constructor(private emitter: EmitterService, private userService: UserService, private authService: AuthService, private router: Router) { 
    this.open = false;
    this.loading = false;
    this.registerForm = new FormGroup({
      name: new FormControl('', [Validators.required, Validators.minLength(2)]),
      lastName: new FormControl('', [Validators.required, Validators.minLength(2)]),
      email: new FormControl('', [Validators.required, Validators.pattern("^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$")]),
      password: new FormControl('', [Validators.required, Validators.minLength(5)]),
      confirmPassword: new FormControl('', [Validators.required, Validators.minLength(5)])
    });
  }

  ngOnInit(): void {
    this.emitter.getValues().subscribe((data) => data.forEach((element: any) => {
      this.open = element.press;
    }));
  }

  onSubmit(): void{
    const user = new User();
    user.firstName = this.registerForm.get('name').value;
    user.lastName = this.registerForm.get('lastName').value;
    user.email = this.registerForm.get('email').value;
    user.password = this.registerForm.get('password').value;
    this.open = false;
    this.loading = true;
    let email = this.registerForm.get("email")?.value;
    let password = this.registerForm.get("password")?.value;
    let credentials = { email: email, password: password }

    this.userService.createUser(user).subscribe((response) => {
      if(response.status === 201){
        
        Swal.fire({
          icon: 'success',
          title: `Cadastro Realizado com Sucesso`,
          text: `Olá ${response.body.firstName}! Seja bem vindo ao Promotion`,
          showConfirmButton: true,
          confirmButtonColor: '#ED7272',
          confirmButtonText: "Vamos lá :P",
        }).then((result) => {
          if (result.isConfirmed){
            this.authService.login(credentials).subscribe((response) => {
              if(response.status === 200){
                let myUser = [{logged: true, admin: false}];
                this.emitter.myValues(myUser);
                this.authService.saveToken(response.body.token)
                this.authService.saveName(response.body.userDTO.firstName)
                this.authService.saveEmail(response.body.userDTO.email)
                this.authService.saveRole(response.body.userDTO.role)
                this.router.navigate(['/home'])
              }
            })
          }
        })
        this.loading = false;
        this.open = false;
      }else{
        Swal.fire({
          icon: 'error',
          title: `Ocorreu um erro no seu cadastro`,
          text: `Tente novamente mais tarde!`,
          showConfirmButton: false,
          timer: 4000,
          timerProgressBar: true
        })
        this.loading = false;
        this.open = true;
      }
    })
  }

  isFormFieldInvalid(field: string) {
    const ctrl = this.registerForm.get(field);
    return ctrl?.dirty && ctrl?.touched && ctrl?.dirty ;
  }

  hasError(field: string, error: string) {
    const ctrl = this.registerForm.get(field);
    return ctrl?.dirty && ctrl?.hasError(error);
  }

  isPasswordDifferent(): boolean{
    const password = this.registerForm.get('password')?.value;
    const confirmPassword = this.registerForm.get('confirmPassword')?.value;
    return password !== confirmPassword;
  }

}
<div class="register animate__animated animate__fadeIn" *ngIf="open">
    <h1>Cadastro</h1>
    <form [formGroup]="registerForm" (submit)="onSubmit()" novalidate class="my-form">
      <label for="name">Nome</label>
      <input [class.is-invalid]="isFormFieldInvalid('name')" formControlName="name" type="text" name="name">
      <div class="messages">
        <small class="text-danger" *ngIf="hasError('name', 'required')">*Campo obrigatório</small>
        <small class="text-danger" *ngIf="hasError('name', 'minlength')">*Tamanho mínimo de 2 caracteres</small>
      </div>
      <label for="lastName">Sobrenome</label>
      <input [class.is-invalid]="isFormFieldInvalid('lastName')" formControlName="lastName" type="text" name="lastName">
      <div class="messages">
        <small class="text-danger" *ngIf="hasError('lastName', 'required')">*Campo obrigatório</small>
        <small class="text-danger" *ngIf="hasError('lastName', 'minlength')">*Tamanho mínimo de 2 caracteres</small>
      </div>
      <label for="email">Email</label>
      <input [class.is-invalid]="isFormFieldInvalid('email')" formControlName="email" type="email" name="email">
      <div class="messages">
        <small class="text-danger" *ngIf="hasError('email', 'required')">*Campo obrigatório</small>
        <small class="text-danger" *ngIf="hasError('email', 'pattern')">*Email inválido</small>
      </div>
      <label for="password">Senha</label>
      <input [class.is-invalid]="isFormFieldInvalid('password')" formControlName="password" type="password" name="password">
      <div class="messages">
        <small class="text-danger" *ngIf="hasError('password', 'required')">*Campo obrigatório</small>
        <small class="text-danger" *ngIf="hasError('password', 'minlength')">*Tamanho mínimo de 5 caracteres</small>
      </div>
      <label for="confirm-password">Confirmar a senha</label>
      <input type="password" name="confirm-password" formControlName="confirmPassword" [class.is-invalid]="isFormFieldInvalid('confirmPassword')">
      <div class="messages">
        <small class="text-danger" *ngIf="hasError('confirmPassword', 'required')">*Campo obrigatório</small>
        <small class="text-danger" *ngIf="isPasswordDifferent() && (registerForm.get('password')?.value != '')">*Senhas diferentes</small>
      </div>
      <button class="btn" type="submit" [disabled]="!registerForm.valid">Cadastrar</button>
    </form>
</div>
<div class="register" *ngIf="loading">
  <loading></loading>
</div>

// frontend-pwa/react/src/components/Register/index.js
import {useState, useRef} from 'react'
import styles from './styles.module.css'
import {Form} from '@unform/web'
import Input from '../Form/Input'
import * as Yup from 'yup'
import UserService from '../../services/UserService'
import Notification, { showToast } from '../../components/Notification'
import Swal from 'sweetalert2'
import withReactContent from 'sweetalert2-react-content'

const Register = () => {

  const formRef = useRef(null);
  const [useToast, setToast] = useState(false);
  const MySwal = withReactContent(Swal)

  async function handleSubmit(data){
    try {
      const schema = Yup.object().shape({
        firstName: Yup.string().required('O nome é obrigatório').min(2, 'No mínimo 2 caracteres').max(20, 'No máximo 20 caracteres'),
        lastName: Yup.string().required('O sobrenome é obrigatório').min(2, 'No mínimo 2 caracteres').max(20, 'No máximo 20 caracteres'),
        email: Yup.string().email('Digite um email válido').required('O email é obrigatório'),
        password: Yup.string().required('A senha é obrigatória').min(5, 'No mínimo 5 caracteres')
      }) 
      
       await schema.validate(data, {
        abortEarly: false
      })

      UserService.createUser(data).then((response) => {
        if(response.status === 201){
          MySwal.fire({
            icon: 'success',
            title: `Cadastro Realizado com Sucesso`,
            text: `Olá ${response.data.firstName}! Seja bem vindo ao Promotion`,
            showConfirmButton: true,
            confirmButtonColor: '#42B983',
            confirmButtonText: "Vamos lá :P",
          }).then((result) => {
            if(result.isConfirmed){
              let userCredentials = {
                email: data.email,
                password: data.password
              }
              console.log(userCredentials)
            }
          })
        }
        else{
          MySwal.fire({
            icon: 'error',
            title: `Ocorreu um erro no seu cadastro`,
            text: `Tente novamente mais tarde!`,
            showConfirmButton: false,
            timer: 4000,
            timerProgressBar: true
          })
        }
      })
      
    } catch (err) {
      setToast(true)
      showToast({ type: "warning", message: "Ocorreu um erro no cadastro, por favor verifique os dados do formulário" });
      if (err instanceof Yup.ValidationError){
        const errorMessages = {}
        err.inner.forEach(error => {
          errorMessages[error.path] = error.message
        })
        formRef.current.setErrors(errorMessages)
      }
    }
  }
  return (
    
    <div className={styles.register}>
      <h1 className={styles.myH1}>Cadastro</h1>
      <Form ref={formRef} onSubmit={handleSubmit} className={styles.myForm}>
        <Input label="Nome" type="text" name="firstName"/>
        <Input label="Sobrenome" type="text" name="lastName" />
        <Input label="Email" type="email" name="email"/>
        <Input label="Senha" type="password" name="password" />
        <div className={"mobileBtn"}><button className={"btn"} type="submit">Cadastrar</button></div>
      </Form>
      {useToast ? <Notification/> : null}
    </div>
  )
}

export default Register
