// frontend-pwa/angular/src/app/pages/promotion/promotion.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Promotion } from 'src/app/models/Promotion';
import { PromotionService } from 'src/app/services/promotion.service';
import { EmitterService } from 'src/app/services/emitter.service';

@Component({
  selector: 'app-promotion',
  templateUrl: './promotion.component.html',
  styleUrls: ['./promotion.component.css']
})
export class PromotionComponent implements OnInit {

  private promotionID: number;
  public promotion: Promotion;
  public myPage: boolean;
  public loading: boolean;

  constructor(private ativatedRoute: ActivatedRoute, private promotionService: PromotionService, private emitter: EmitterService) { 
    
  }

  ngOnInit(): void {
    this.loading = true;
    this.myPage = false;
    this.ativatedRoute.params.subscribe((params) => {
      this.promotionID = params['id'];
    })

    this.promotionService.getPromotionById(this.promotionID).subscribe((response) => {
      this.promotion = response;
      this.loading = false;
      this.myPage = true;
    })
  }

  likePromotion(event){
    this.promotionService.like(event.id).subscribe((res) => {
      this.promotion = res;
    })
  }

  goToWebSite(urlLink){
    return window.open(urlLink, '_blank') 
  }
}

<section class="promotion-section animate__animated animate__fadeIn">
  <div class="promotion" *ngIf="myPage">
    <back></back>
    <like [likes]="promotion?.numberLikes" class="like" [promotionID]="promotion?.id" (update)="likePromotion($event)" class="like"></like>
    <div class="my-img">
      <img [src]=promotion?.photo alt="{{promotion?.name}}">
    </div>
    <div class="my-price">
      <p>{{promotion?.price | currency:'BRL':true}}</p>
  </div>
  <div class="my-info">
    <h3>{{promotion?.name}}</h3>
    <div class="my-local">
        <p>Vendido por {{promotion?.soldBy}}</p>
    </div>
    <div class="description">
      <p>{{promotion?.description}}</p>
    </div>
  </div>
  <div class="my-buttons">
    <p [ngStyle]="{'display' : promotion?.voucher.length === 0 ? 'none' : 'flex'}" class="my-cupom">Cupom: {{promotion?.voucher}}</p>
    <button [ngStyle]="{'margin' : promotion?.voucher.length === 0 ? '0 auto' : 'none'}" class="btn" (click)= "goToWebSite(promotion?.urlLink)">Acessar</button>
  </div>
  
  <div class="person">
    <ngx-avatar class="my-avatar" bgColor="#F4E6E6" fgColor="#ED9292" name={{promotion?.user.firstName}} size="40"> </ngx-avatar>
    <div class="data">
        <p>Postado por {{promotion?.user.firstName}}</p>
        <p>{{promotion?.date | dateAgo}}</p>
    </div>
  </div>
  </div>
<div class="myLoading" *ngIf="loading"> 
  <loading ></loading>
</div>
</section>

// frontend-pwa/react/src/pages/Promotion/index.js
import {useState, useEffect} from 'react'
import './promotion.css'
import Back from '../../components/Back'
import Avatar from 'react-avatar';
import PromotionService from '../../services/PromotionService';
import Loading from '../../components/Loading';
import { useParams } from 'react-router-dom'
import Like from '../../components/Like';
import toCurrency from '../../filters/toCurrency'
import dateAgo from '../../filters/dateAgo'
import {Animated} from "react-animated-css";


const Promotion = () => {
  const params = useParams();
  const [loading, setLoading] = useState(false)
  const [promotion, setPromotion] = useState("")
  let loadingStyle = {
    background: 'none'
  }

  useEffect(() => {
    setLoading(true)
    PromotionService.getPromotionById(params.id).then((response) => {
      if(response.status === 200){
        setPromotion(response.data)
        setLoading(false)
      }
    })
  }, [params.id])

  function goToWebSite(urlLink){
    return window.open(urlLink, '_blank') 
  }

  function likePromotion(){
    PromotionService.like(params.id).then((response) => {
      if(response.status === 200){
        setPromotion(response.data)
      }
    })
  }

  return (
  <Animated animationIn="fadeIn" animationOut="fadeOut" isVisible={true}>
  <section className="promotionSection">
      {loading ? <div style={loadingStyle} className={"myDiv"} >
        <Loading/>
      </div> :
  <div className="promotion">
    <Back/>
    <div className="myLike">
      <Like onClick={likePromotion} likes={promotion.numberLikes}></Like >
    </div>
    <div className="promotionImg">
      <img src={promotion.photo} alt="promotion"/>
    </div>
    <div className="promotionPrice">
      <p>{toCurrency(promotion.price)}</p>
  </div>
  <div className="promotionInfo">
    <h3>{promotion.name}</h3>
    <div className="promotionLocal">
        <p>Vendido por {promotion.soldBy}</p>
    </div>
    <div className="description">
      <p>{promotion.description}</p>
    </div>
  </div>
  <div className="promotionBtns">
    {promotion.voucher === "" ? <p className="myCupom">Sem Cupom</p> : <p className="myCupom">Cupom: {promotion.voucher} </p>}
   
    <button className={"btn"} onClick={() => {goToWebSite(promotion.urlLink)}}>Acessar</button>
  </div>
  
  <div className="promotionPerson">
  <Avatar color="#beebf7" name={promotion.user?.firstName} size="35" round={true} />
    <div className="dataPerson">
        <p>Postado por {promotion.user?.firstName}</p>
        <p>{dateAgo(promotion.date)}</p>
    </div>
  </div>
  </div>}

</section>
</Animated>

  )
}

export default Promotion
